routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ButikController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\TreatmentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::get('lang/{lang}', [LocalizationController::class, 'switchLang'])->name('lang.switch');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('butiks', ButikController::class);

    //PATIENTS
    Route::resource('patients', PatientController::class);
    // Search function
    Route::post('patients/search', ['as' => 'patients.search', 'uses' => 'App\Http\Controllers\PatientController@search']);

    //AVATAR
    // Activate
    Route::get('/profile/activate', '\App\Http\Controllers\ProfileController@activateAvatar')->name('profile.activate');
    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', ['uses' => 'App\Http\Controllers\ProfileController@userProfileAvatar',]);
    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'App\Http\Controllers\ProfileController@upload']);

    //BUTIK IMAGE
    // Route to upload Butik Image.
    Route::post('butiks/upload/{id}', ['as' => 'butiks.upload', 'uses' => 'App\Http\Controllers\ButikController@upload']);

    //PROFILE
    //    Route::resource('profile', ProfileController::class, ['only' => ['index']]);
    Route::get('/profile/{username}', '\App\Http\Controllers\ProfileController@index')->name('profile.index');
    Route::get('/profile/{username}/edit', '\App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::get('/profile/{username}/create', '\App\Http\Controllers\ProfileController@createProfile')->name('profile.create');
    Route::match(['put', 'patch'], '/profile/{username}/update', '\App\Http\Controllers\ProfileController@update')->name('profile.update');
    Route::put('/profile/{username}/updateUserAccount', '\App\Http\Controllers\ProfileController@updateUserAccount')->name('profile.updateUserAccount');
    Route::put('/profile/{username}/updateUserPassword', '\App\Http\Controllers\ProfileController@updateUserPassword')->name('profile.updateUserPassword');

    //TREATMENT
    Route::resource('treatments', TreatmentController::class);
    Route::get('/treatments/patient/{patient}', 'App\Http\Controllers\TreatmentController@index')->name('treatment.patient');
    Route::get('/treatments/create/{treatment}', 'App\Http\Controllers\TreatmentController@create')->name('treatment.create');
});

resources/views/partials/footer.blade.php
<div></div>
<div class="ml-auto">Powered by&nbsp;<a href="https://coreui.io/">CoreUI</a></div>

resources/views/partials/form-status.blade.php
@if (session('message'))
    <div class="alert alert-{{ Session::get('status') }} status-box alert-dismissable fade show" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;<span class="sr-only">Close</span></a>
        {{ session('message') }}
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h4><i class="icon fa fa-check fa-fw" aria-hidden="true"></i> Success</h4>
        {{ session('success') }}
    </div>
@endif

@if(session()->has('status'))
    @if(session()->get('status') == 'wrong')
        <div class="alert alert-danger status-box alert-dismissable fade show" role="alert">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;<span class="sr-only">Close</span></a>
            {{ session('message') }}
        </div>
    @endif
@endif

@if (session('error'))
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h4>
            <i class="icon fa fa-warning fa-fw" aria-hidden="true"></i>
            Error
        </h4>
        {{ session('error') }}
    </div>
@endif

@if (session('errors') && count($errors) > 0)
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <h4>
            <i class="icon fa fa-warning fa-fw" aria-hidden="true"></i>
            <strong>@lang('auth.whoops')</strong> @lang('auth.someProblems')
        </h4>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/partials/login-footer.blade.php
<div></div>
<div class="ml-auto">Powered by&nbsp;<a href="https://coreui.io/">CoreUI</a></div>

resources/views/partials/login-navbar.blade.php
<nav class="navbar">
    <div class="c-sidebar-brand-full">
        <i class="fa fa-heartbeat fa-3x" aria-hidden="true" style="color: red"></i>
    </div>
    <h4 class="ml-2 white-text">Butik@Sihat2U</h4>
</nav>

resources/views/partials/navbar.blade.php
<button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
    <i class="c-icon c-icon-lg cil-menu"></i>
</button>
<a class="c-header-brand d-lg-none" href="#">
    <i class="c-icon c-icon-lg cib-full"></i>
</a>
<button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
    <i class="c-icon c-icon-lg cil-menu"></i>
</button>

<ul class="c-header-nav mfs-auto">
</ul>

<ul class="c-header-nav ml-auto">
    <li class="c-header-nav-item dropdown">
        <a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
           aria-expanded="false">
            <div class="c-avatar">
                @if ((Auth::User()->profile) && Auth::user()->profile->avatar_status == 1)
                    @if(!empty(Auth::user()->profile->avatar))
                        <img src="{{ Auth::user()->profile->avatar }}" alt="{{ Auth::user()->username }}"
                             class="c-avatar-img user-avatar-nav border border-dark">
                    @else
                        <div class="c-avatar-img user-avatar-nav"><i class="fas fa-user-circle fa-2x pl-2"></i></div>
                    @endif
                @else
                    <div class="c-avatar-img user-avatar-nav"><i class="fas fa-user-circle fa-2x pl-2"></i></div>
                @endif
            </div>
        </a>

        <div class="dropdown-menu dropdown-menu-right pt-0">
            <div class="dropdown-header bg-light py-2 text-center"><strong>{{Auth::user()->username}}</strong></div>
            <a class="dropdown-item" href="{{ route('profile.index',Auth::user()->username) }}">
                <i class="c-icon mfe-2 cil-user"></i> {{trans('navbar.profile')}}
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                <i class="cil-account-logout mr-2"></i> {{trans('navbar.logout')}}
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </div>
    </li>
</ul>

resources/views/partials/sidebar.blade.php
<div class="c-sidebar-brand d-lg-down-none">
    <div class="c-sidebar-brand-full">
        <i class="fa fa-heartbeat fa-3x" aria-hidden="true" style="color: red"></i>
    </div>
    <div class="c-sidebar-brand-minimized">
        <i class="fa fa-heartbeat fa-2x" aria-hidden="true" style="color: red"></i>
    </div>
</div>
<ul class="c-sidebar-nav">
    <li class="c-sidebar-nav-item">
        <a class="c-sidebar-nav-link" href="{{route('home')}}"> <i class="c-sidebar-nav-icon cil-speedometer"></i>Dashboard</a>
    </li>
    @if(Auth::user()->hasRole('System Admin'))
        <li class="c-sidebar-nav-title">{{trans('sidebar.adminDropdownNav')}}</li>
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="{{ route('users.index') }}">
                <i class="c-sidebar-nav-icon cil-user"></i>{{trans('sidebar.adminUsers')}}
            </a>
        </li>
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="{{ route('roles.index') }}">
                <i class="c-sidebar-nav-icon cil-shield-alt"></i>{{trans('sidebar.usersRole')}}
            </a>
        </li>
    @endif
    @if(Auth::user()->can('butik-list'))
        <li class="c-sidebar-nav-title">{{trans('sidebar.butik')}}</li>
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="{{ route('butiks.index') }}">
                <i class="c-sidebar-nav-icon cil-hospital"></i>{{trans('sidebar.butik-list')}}
            </a>
        </li>
    @endif
    @if(Auth::user()->can('patient-list'))
        <li class="c-sidebar-nav-title">{{trans('sidebar.patients')}}</li>
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="{{ route('patients.index') }}">
                <i class="c-sidebar-nav-icon cil-search"></i>{{trans('sidebar.patients-search')}}
            </a>
        </li>
        @can('patient-create')
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="{{ route('patients.create') }}">
                    <i class="c-sidebar-nav-icon cil-group"></i>{{trans('sidebar.patients-register')}}
                </a>
            </li>
        @endcan
    @endif
    <li class="c-sidebar-nav-title">Components</li>
    <li class="c-sidebar-nav-item c-sidebar-nav-dropdown">
        <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
            <i class="c-sidebar-nav-icon cil-cursor"></i> Buttons</a>
        <ul class="c-sidebar-nav-dropdown-items">
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="#"><span
                        class="c-sidebar-nav-icon"></span> Buttons</a></li>
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="#"><span
                        class="c-sidebar-nav-icon"></span> Buttons Group</a></li>
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="#"><span
                        class="c-sidebar-nav-icon"></span> Dropdowns</a></li>
            <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="#"><span
                        class="c-sidebar-nav-icon"></span> Brand Buttons</a></li>
        </ul>
    </li>

    <li class="c-sidebar-nav-title  mt-auto">@lang('sidebar.language')</li>
    @foreach (Config::get('languages') as $lang => $language)
        @if ($lang != App::getLocale())
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link" href="{{ route('lang.switch', $lang) }}">
                    <i class="c-sidebar-nav-icon cif-{{$language['flag-icon']}}"></i>{{$language['display']}}
                </a>
            </li>
        @endif
    @endforeach
</ul>
<button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent"
        data-class="c-sidebar-minimized"></button>